create table if not exists public."سجلات النظام" (
  log_id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  action text not null,
  user_type text not null check (user_type in ('student', 'supervisor', 'system')),
  user_id text,
  username text,
  ip_address inet,
  device_id text,
  device_type text,
  user_agent text,
  platform text,
  language text,
  screen_size text,
  path text,
  details jsonb not null default '{}'::jsonb
);

create index if not exists system_logs_created_at_idx
  on public."سجلات النظام" (created_at desc);

create index if not exists system_logs_user_idx
  on public."سجلات النظام" (user_type, user_id, username);

create index if not exists system_logs_action_idx
  on public."سجلات النظام" (action);

alter table public."سجلات النظام" enable row level security;

drop policy if exists "system logs can be created"
  on public."سجلات النظام";

create policy "system logs can be created"
  on public."سجلات النظام"
  for insert
  to anon, authenticated
  with check (true);

drop policy if exists "system logs can be read"
  on public."سجلات النظام";

create policy "system logs can be read"
  on public."سجلات النظام"
  for select
  to anon, authenticated
  using (true);

