alter table if exists public."الحضور"
  add column if not exists "الحالة" text default 'غير محدد';

alter table if exists public."الحضور"
  add column if not exists "تفاصيل الغياب" text;

alter table if exists public."الحضور"
  add column if not exists "المشرف" text;

alter table if exists public."الحضور"
  add column if not exists "الوقت" time;

alter table if exists public."الإنذارات"
  add column if not exists "المشرف" text;

alter table if exists public."الإنذارات"
  add column if not exists "الوقت" time;

create index if not exists attendance_student_id_idx
  on public."الحضور" ("الرقم الجامعي");

create index if not exists warnings_student_id_idx
  on public."الإنذارات" ("الرقم الجامعي");

create table if not exists public."إنذارات المشرفين" (
  warning_id bigint generated by default as identity primary key,
  "اسم المستخدم" text not null,
  "الدرجة" text not null,
  "التفاصيل" text not null,
  "أنشأه" text not null,
  "التاريخ" date not null default current_date,
  "الوقت" time not null default current_time
);

alter table public."إنذارات المشرفين" enable row level security;

drop policy if exists "supervisor warnings can be read"
on public."إنذارات المشرفين";

create policy "supervisor warnings can be read"
on public."إنذارات المشرفين"
for select
to anon, authenticated
using (true);

drop policy if exists "supervisor warnings can be created"
on public."إنذارات المشرفين";

create policy "supervisor warnings can be created"
on public."إنذارات المشرفين"
for insert
to anon, authenticated
with check (true);
