import { supabase } from './supabase';

export type StudentRow = {
  id?: number | string;
  'الرقم الجامعي'?: string | number;
  'كلمة السر'?: string;
  'اسم الطالب'?: string;
  'اسم الاب'?: string;
  'الكنية'?: string;
  'القسم'?: string;
  'رقم الهاتف'?: string;
  'نوع التسجيل'?: string;
  'ملاحظة'?: string;
  'البريد الإلكتروني'?: string;
  'الفئة'?: string;
  'تاريخ_تغيير_الفئة'?: string | null;
  'تاريخ الإنشاء'?: string | null;
  'السنه الدراسية'?: string | number;
  class?: string;
  year?: string;
  password?: string;
  name?: string;
  student_id?: string | number;
  studentId?: string | number;
  ['الرقم']?: string | number;
};

export const fieldAliases = {
  studentId: ['الرقم الجامعي', 'student_id', 'studentId', 'الرقم', 'id'],
  password: ['كلمة السر', 'password', 'pass'],
  studentName: ['اسم الطالب', 'student_name', 'name', 'الاسم'],
  className: ['الفئة', 'class', 'class_name', 'الفئة_الجامعية'],
  year: ['السنه الدراسية', 'السنة الدراسية', 'year', 'student_year'],
  section: ['القسم', 'section', 'department'],
  status: ['الحالة', 'status', 'الحالة_الدراسية'],
};

export const normalizeText = (value: unknown) => {
  if (value === null || value === undefined || value === '') return 'غير متوفر';
  return String(value).trim();
};

export const getRecordValue = (row: Record<string, unknown>, keys: string[]) => {
  for (const key of keys) {
    const value = row[key];
    if (value !== null && value !== undefined && value !== '') return value;
  }
  return undefined;
};

export const getStudentId = (student: Partial<StudentRow>) => {
  const value = getRecordValue(student as Record<string, unknown>, fieldAliases.studentId);
  return value === undefined ? '' : String(value).trim();
};

const warningIdCandidates = ['warnig_id', 'warning_id', 'warningId', 'warnigId', 'id'];

const stripAutoGeneratedWarningIds = (payload: Record<string, unknown>) => {
  const sanitized = { ...payload };
  warningIdCandidates.forEach((key) => delete sanitized[key]);
  return sanitized;
};

export const findWarningIdKey = (row: Record<string, unknown>) => {
  const key = warningIdCandidates.find((candidate) => {
    const value = row[candidate];
    return value !== null && value !== undefined && value !== '';
  });

  return key ?? 'warnig_id';
};

export const getTableRows = async (tableNames: string[]) => {
  for (const tableName of tableNames) {
    const { data, error } = await supabase.from(tableName).select('*');
    if (!error) {
      return { data: (Array.isArray(data) ? data : []) as Record<string, unknown>[], tableName };
    }

    const message = String(error.message || '').toLowerCase();
    if (message.includes('does not exist') || message.includes('relation') || message.includes('not found')) {
      continue;
    }

    return { data: [], tableName, error };
  }

  return { data: [], tableName: tableNames[0], error: null };
};

export const getStudentById = async (studentId: string) => {
  const tables = ['students'];
  for (const tableName of tables) {
    const { data, error } = await supabase.from(tableName).select('*');
    if (error) {
      const message = String(error.message || '').toLowerCase();
      if (message.includes('does not exist') || message.includes('relation') || message.includes('not found')) {
        continue;
      }
      throw error;
    }

    const rows = Array.isArray(data) ? (data as StudentRow[]) : [];
    const match = rows.find((row) => getStudentId(row) === String(studentId).trim());
    if (match) return match;
  }

  return null;
};

export const getStudentsByClass = async (classGroup: string, yearFilter = '') => {
  const rows = await getTableRows(['students']);
  const data = rows.data as StudentRow[];

  return data.filter((student) => {
    const classValue = normalizeText(getRecordValue(student as Record<string, unknown>, fieldAliases.className)).replace('فئة ', '');
    const yearValue = normalizeText(getRecordValue(student as Record<string, unknown>, fieldAliases.year));
    const classMatches = !classGroup || classValue === classGroup || classValue === `فئة ${classGroup}`;
    const yearMatches = !yearFilter || yearValue === yearFilter;
    return classMatches && yearMatches;
  });
};

export const recordAttendance = async (student: Partial<StudentRow>, course: string, classValue: string, status: 'pending' | 'present' | 'absent') => {
  const studentId = getStudentId(student);
  if (!studentId) return false;

  const payload = {
    'الرقم الجامعي': studentId,
    'اسم الطالب': normalizeText(getRecordValue(student as Record<string, unknown>, fieldAliases.studentName)),
    'الفئة': classValue,
    'المادة': course,
    'الحالة': status === 'present' ? 'حاضر' : status === 'absent' ? 'غائب' : 'بانتظار',
    'التاريخ': new Date().toISOString(),
    'السنه الدراسية': normalizeText(getRecordValue(student as Record<string, unknown>, fieldAliases.year)),
  };

  const attendanceTables = ['attendance', 'الحضور', 'حضور'];
  for (const tableName of attendanceTables) {
    try {
      const { error } = await supabase.from(tableName).insert([payload]);
      if (!error) return true;
      const message = String(error.message || '').toLowerCase();
      if (message.includes('does not exist') || message.includes('relation') || message.includes('not found')) {
        continue;
      }
      console.error(`Attendance insert failed for ${tableName}:`, error.message);
      return false;
    } catch (error) {
      console.error('Attendance insert threw', error);
    }
  }

  return false;
};

export const recordWarning = async (student: Partial<StudentRow>, course: string, classValue: string, reason = 'غياب') => {
  const studentId = getStudentId(student);
  if (!studentId) return false;

  const payload = stripAutoGeneratedWarningIds({
    'الرقم الجامعي': studentId,
    'اسم الطالب': normalizeText(getRecordValue(student as Record<string, unknown>, fieldAliases.studentName)),
    'نوع الإنذار': 'إنذار غياب',
    'السبب': `غياب في مادة ${course || 'غير محددة'}`,
    'التفاصيل': '',
    'تم الإرسال': true,
  });

  try {
    const { error } = await supabase.from('الإنذارات').insert([payload]);
    if (!error) return true;
    console.error('Warning insert failed for جدول الإنذارات:', error.message);
    return false;
  } catch (error) {
    console.error('Warning insert threw', error);
    return false;
  }
};

export const updateWarningById = async (warningId: string | number, updates: Record<string, unknown>) => {
  const idString = String(warningId ?? '').trim();
  if (!idString) return { success: false, error: 'missing-warning-id' };

  const tableNames = ['الإنذارات', 'warnings', 'warning'];

  for (const tableName of tableNames) {
    const { data, error } = await supabase.from(tableName).select('*');
    if (error) {
      const message = String(error.message || '').toLowerCase();
      if (message.includes('does not exist') || message.includes('relation') || message.includes('not found')) {
        continue;
      }
      return { success: false, error: error.message };
    }

    const rows = Array.isArray(data) ? (data as Record<string, unknown>[]) : [];
    const match = rows.find((row) => warningIdCandidates.some((key) => String(row[key] ?? '') === idString));
    if (!match) continue;

    const actualKey = findWarningIdKey(match);
    const { error: updateError } = await supabase.from(tableName).update(updates).eq(actualKey, idString);
    if (updateError) {
      return { success: false, error: updateError.message };
    }

    return { success: true, tableName, field: actualKey };
  }

  return { success: false, error: 'warning-not-found' };
};

export const deleteWarningById = async (warningId: string | number) => {
  const idString = String(warningId ?? '').trim();
  if (!idString) return { success: false, error: 'missing-warning-id' };

  const tableNames = ['الإنذارات', 'warnings', 'warning'];

  for (const tableName of tableNames) {
    const { data, error } = await supabase.from(tableName).select('*');
    if (error) {
      const message = String(error.message || '').toLowerCase();
      if (message.includes('does not exist') || message.includes('relation') || message.includes('not found')) {
        continue;
      }
      return { success: false, error: error.message };
    }

    const rows = Array.isArray(data) ? (data as Record<string, unknown>[]) : [];
    const match = rows.find((row) => warningIdCandidates.some((key) => String(row[key] ?? '') === idString));
    if (!match) continue;

    const actualKey = findWarningIdKey(match);
    const { error: deleteError } = await supabase.from(tableName).delete().eq(actualKey, idString);
    if (deleteError) {
      return { success: false, error: deleteError.message };
    }

    return { success: true, tableName, field: actualKey };
  }

  return { success: false, error: 'warning-not-found' };
};

export const getWarningsForStudent = async (studentId: string) => {
  const { data } = await getTableRows(['الإنذارات']);
  return (data as Record<string, unknown>[]).filter((row) => {
    const rowId = String(getRecordValue(row, ['الرقم الجامعي']) ?? '');
    return rowId === String(studentId).trim();
  });
};

export const getAttendanceForStudent = async (studentId: string) => {
  const { data } = await getTableRows(['الحضور']);
  return (data as Record<string, unknown>[]).filter((row) => {
    const rowId = String(getRecordValue(row, ['الرقم الجامعي', 'student_id', 'studentId']) ?? '');
    return rowId === String(studentId).trim();
  });
};

export const getStudentMarksForStudent = async (studentId: string) => {
  const candidateTables = ['الاعمال', 'الأعمال', 'أعمال', 'العملي', 'النظري', 'works', 'student_works'];
  const merged: Record<string, unknown>[] = [];

  for (const tableName of candidateTables) {
    const { data } = await getTableRows([tableName]);
    if (!Array.isArray(data)) continue;
    merged.push(...(data as Record<string, unknown>[]));
  }

  return merged.filter((row) => {
    const rowId = String(getRecordValue(row, ['الرقم الجامعي', 'student_id', 'studentId']) ?? '');
    return rowId === String(studentId).trim();
  });
};
